# Generated by Django 3.1.5 on 2021-02-08 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_userprofileinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='portfolio_site',
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='about_you',
            field=models.CharField(default='You are enthusiastic', max_length=50),
        ),
    ]
