# Generated by Django 3.1.5 on 2021-02-09 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_auto_20210208_2332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=200)),
                ('prod_details', models.CharField(max_length=256)),
                ('prod_price', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='about_you',
            field=models.EmailField(max_length=254),
        ),
    ]
