# Generated by Django 3.1.5 on 2021-02-09 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_auto_20210209_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_img',
            field=models.ImageField(default='upload IMG', upload_to=''),
        ),
        migrations.AlterField(
            model_name='products',
            name='prod_price',
            field=models.PositiveIntegerField(),
        ),
    ]
