# Generated by Django 3.1.5 on 2021-02-09 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_auto_20210209_1534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='about_you',
            new_name='email',
        ),
    ]
