# Generated by Django 3.1.5 on 2021-02-10 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0013_auto_20210210_1237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='category',
            new_name='item',
        ),
    ]
