# Generated by Django 3.1.5 on 2021-02-19 08:50

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0017_auto_20210219_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='user',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='purchased',
            field=models.CharField(choices=[('0', 'No'), ('1', 'Yes')], default='0', max_length=5),
        ),
        migrations.AddField(
            model_name='products',
            name='stock',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='address',
            field=models.ManyToManyField(related_name='profile_address', to='ecommerce.Address'),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='alternate_mobile_no',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='mobile_no',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
