# Generated by Django 3.1.5 on 2021-02-20 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0020_auto_20210220_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='address',
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='address',
            field=models.TextField(max_length=250, null=True),
        ),
    ]
