# Generated by Django 3.1.5 on 2021-02-20 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0022_auto_20210220_1353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='user_id',
            new_name='user',
        ),
    ]
