# Generated by Django 3.1.5 on 2021-02-23 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0023_auto_20210220_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pname',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
