# Generated by Django 3.1.5 on 2021-02-24 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0025_auto_20210223_1348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='customer',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='user',
        ),
    ]
