# Generated by Django 3.1.5 on 2021-02-24 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0026_auto_20210224_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='user',
            field=models.CharField(max_length=200),
        ),
    ]
