# Generated by Django 3.1.5 on 2021-02-24 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0027_auto_20210224_1129'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfileInfo',
            new_name='Customer',
        ),
    ]
