# Generated by Django 3.1.5 on 2021-02-24 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0030_auto_20210224_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pname',
            field=models.CharField(max_length=32),
        ),
    ]
