# Generated by Django 3.1.5 on 2021-02-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0031_auto_20210224_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=32)),
                ('quan', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='pname',
        ),
    ]
