# Generated by Django 3.1.5 on 2021-02-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0032_auto_20210224_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='prod_img',
            field=models.ImageField(default='ecommerce/p1.jpg', null=True, upload_to='ecommerce/'),
        ),
    ]
