# Generated by Django 3.1.5 on 2021-02-25 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0037_auto_20210225_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='quan',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
