# Generated by Django 3.1.5 on 2021-02-25 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0039_auto_20210225_1318'),
    ]

    operations = [
        migrations.DeleteModel(
            name='stock',
        ),
    ]
