# Generated by Django 3.1.5 on 2022-01-04 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0040_delete_stock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User1',
        ),
    ]
