# Generated by Django 3.1.5 on 2022-01-04 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0041_delete_user1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='quan',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
